export const MOCK_INTERVIEW_JOBS = [
  {
    title: "Web Developer (Javascript)",
    company: "Applogiq",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=77c57d122fc1a304&bb=qnz2XNJD0S_P_Q6YhF7-kjtCQr6tOsTg-7LqJtwuAQ7H0aAVgV3gd0g-ch4tY6Zps2A_ujkeTmW7vxV8Q9HPxl6kFz1DTQdbN7O4qJi1IEuKE4H-ql6vqNVQMLIDlwRZ&xkcb=SoAv67M3kYpAN4gfYj0KbzkdCdPP&fccid=f24ee608be132809&cmp=ApplogiQ&ti=Web+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Front-End Developer",
    company: "Innoboon",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=6208d8a0d50ff680&bb=qnz2XNJD0S_P_Q6YhF7-kjwBomnd1H1vCdEqhAHU8dKsPMErlcy9QGQ0vL7etRXxpzyGMBzwXTfYSiqU2RlnF3aZ6W1c6y_G_bzwSlWUhH8uUkriFW8mLYrpMrLAE4ZH&xkcb=SoCy67M3kYpAN4gfYj0JbzkdCdPP&fccid=7fb938b853acdeeb&vjs=3",
    source: "indeed",
  },
  {
    title: "Fresher (Batch 2026) | Software Developer",
    company: "Nobl Q",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=64cf89b6424b9707&bb=qnz2XNJD0S_P_Q6YhF7-kqCMIKf0ulSwfSTeNJUQ1UxA80Y0vJj6iYKkZx8RHkVjNl_bX5oCe9ySahf8tdHU9bz_uRLE33Bhlxz50fNJoSG_biVmW3k4LVtCRNTDaK8w&xkcb=SoAG67M3kYpAN4gfYj0IbzkdCdPP&fccid=9c4faf4442f46cc9&vjs=3",
    source: "indeed",
  },
  {
    title: "React JS Developer",
    company: "App Innovation Technologies",
    location: "Gnanambika Mills, Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=4ef60fd9cb02e755&bb=qnz2XNJD0S_P_Q6YhF7-kvf4JxjVUSD1-pMSEN3RnrG72ehUZB42Q6LCCv-f2NgLFpxlZs3ThP1angosTNJY6drpwCRQst3ZDt5qQ3KsHjlkMy86ex_tIUf6oX7GP2KH&xkcb=SoCI67M3kYpAN4gfYj0PbzkdCdPP&fccid=956d1090136877de&cmp=App-Innovation-Technologies&ti=Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "React JS Developer",
    company: "App Innovation Technologies",
    location: "Gnanambika Mills, Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/viewjob?jk=123456789abcdef0",
    source: "indeed",
  },
  {
    title: "Front End Developer",
    company: "App Innovation Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=bbc0ca04196a511b&bb=qnz2XNJD0S_P_Q6YhF7-knyuD4DSJLvNa-V_OjLwQ0aH2p47aG7kL-jrTn-bz45JDwTbTU3R2zdt7doqg1t8jyJAACXQnLuwH0Hf_zJ3aEDf6Q2spOJ4WMTPDhA3H2vt&xkcb=SoA867M3kYpAN4gfYj0ObzkdCdPP&fccid=956d1090136877de&cmp=App-Innovation-Technologies&ti=Front+End+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Junior Developer (Backend)",
    company: "Shloklabs",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=cdd5842187c75685&bb=qnz2XNJD0S_P_Q6YhF7-kgx1md3Jt1kdOXnQu1DZRQAAdnMRFka9HMW4P8hJfVPORo7_dufeH4x0GHrXuxptsjGxXlDjLXs1kzsv2kC0ghMjWZRec3SszmMn_-6-7uHh&xkcb=SoAV67M3kYpAN4gfYj0MbzkdCdPP&fccid=ba2dad8deaa042cd&vjs=3",
    source: "indeed",
  },
  {
    title: "Full Stack Developer",
    company: "Invicious Metacorp Private Limited",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=af7b84c4274d307a&bb=qnz2XNJD0S_P_Q6YhF7-khf90EAyX6oWVwbtJop6dqs82JFjKoOIaQ4H608KFmUWmX3C7WJ-fJ-Wa_opHarYZMoQN9nzE1WJfSM3U8GJIBY0ZPfgOzqjwvgSC0IgIwvn&xkcb=SoD867M3kYpAN4gfYj0DbzkdCdPP&fccid=4e9776af8774e13a&cmp=Invicious-Metacorp-Private-Limited&ti=Full+Stack+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Software Developer",
    company: "Comgen India Software Solution Pvt. Ltd.",
    location: "Saravanampatti, Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=95d412dfc80f69f0&bb=qnz2XNJD0S_P_Q6YhF7-kqHsEVxPkA396yyfau_pPOkt8udbnH8aAjXxm7hrIDb9qLYX26xfSdsAhlc2GKT8JQLmbrX4QV_Wl4z4naqyK_78_8uO5Jpsj2yYK9GWYhON&xkcb=SoBI67M3kYpAN4gfYj0CbzkdCdPP&fccid=f8f878c352ac6337&cmp=comgen-india-software-solution-company&ti=Software+Engineer&vjs=3",
    source: "indeed",
  },
  {
    title: "Trainee Software Engineer",
    company: "CAP Digisoft Solutions",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=6d7a1fa9033b547f&bb=qnz2XNJD0S_P_Q6YhF7-kk_BKqFFgPdWjDL1fJwd-vi64E4VR8oCQbqPNoEd3nzLt1swgY4_QyPo93DI23pDgs22LzgcIPlMZl7jM7dVOiVJl_WdlCw5TnElYGapiKcW&xkcb=SoDV67M3kYpAN4gfYj0BbzkdCdPP&fccid=b2054667c102898d&vjs=3",
    source: "indeed",
  },
  {
    title: "Senior React JS Developer",
    company: "Sumanas Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=5947ce2f54f92823&bb=qnz2XNJD0S_P_Q6YhF7-kjtCQr6tOsTgB4Xj8ShBdita8TBNsLcqM3i__cLXlUAQQXocI5SUfrEsBfFVyEahVpGxhAQxeQjU00SFbLzeosW0S46oUyo7h4piq2TEoJej&xkcb=SoBh67M3kYpAN4gfYj0AbzkdCdPP&fccid=77c57e2a11faa4fb&vjs=3",
    source: "indeed",
  },
  {
    title: "React Native Developer",
    company: "GUHATEK CONSULTING SERVICES PRIVATE LIMITED",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=8239de3f67e91210&bb=qnz2XNJD0S_P_Q6YhF7-kp8QKmwWd4bw5waLJKCfjU0MJjx7h7QwiTfIcYef-4FAHVcmqmXgNmSMt-PvAkalT332LFy8pD5qPxphWhSH2f0kgisIO4c79jgeFoBVdbde&xkcb=SoDv67M3kYpAN4gfYj0HbzkdCdPP&fccid=102d938e67e8b59c&cmp=GUHATEK-CONSULTING-SERVICES-PRIVATE-LIMITED&ti=Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Frontend Developer (2–3 Years Experience)",
    company: "Conceps Media Works",
    location: "Peelamedu, Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=55a3b913b85b81fa&bb=qnz2XNJD0S_P_Q6YhF7-kstGe5NoC_OBjBOmiMozcykswopLqx2fijbUAX5KO7iP9HbcjZgC0syEBgXAKvI6-OdyEu8W6hnj560NqNq_-xgM_aOz1xUDUYw3c4zZZ9I0&xkcb=SoBb67M3kYpAN4gfYj0GbzkdCdPP&fccid=1580c1f1340c84d0&cmp=Conceps-Media-Works&ti=Front+End+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Web Developer",
    company: "G2TechSoft",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=c3171b6133a2f8d8&bb=qnz2XNJD0S_P_Q6YhF7-khsxfRUsSySbEO1xOw2vTHtPnMH_vBx3UyUiAgcCO-ODgY7Pf5rGbkkly2vssVzwlAiXrWQT3CqRzMDf2LJ9EhHIT1l4Z_P-vkTBCkDWM1cJ&xkcb=SoBy67M3kYpAN4gfYj0EbzkdCdPP&fccid=de01dc8ebc8367c8&vjs=3",
    source: "indeed",
  },
  {
    title: "Mobile Application Developer – React Native (Intern)",
    company: "Avanexa Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=13f92ff879f6fad2&bb=HtY44tjKAMlRZeFarjJnvioG-Cz1aCqiHButAxrNhDSON2dnWPalr9CARqC60jMFwJUVLJ4qT41r5I_q_JjHTZG7UDjBYRPtKPnRiDygXQUgOyJy1SNj1d7RWiqUgSmP&xkcb=SoD067M3kYpaPMgfTT0LbzkdCdPP&fccid=2590537f1d5cfafe&vjs=3",
    source: "indeed",
  },
  {
    title: "Full Stack Developer (Coimbatore) (Immediate Join)",
    company: "Smitiv Mobile Technologies- A Singapore based App...",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=21ce6da0dcf29f48&bb=HtY44tjKAMlRZeFarjJnvqXjLiJ0InoiHH684x0nVDp3pSd25w-77JlZWf3-zEzxxTFSTnn_Rrw0HHzZhkyIPOodb8BWOkkokmjPmcmYfpQUsAjlAfbMz_vjGJgIQUJP&xkcb=SoBA67M3kYpaPMgfTT0KbzkdCdPP&fccid=129cd09470ff6826&vjs=3",
    source: "indeed",
  },
  {
    title: "Web Developer",
    company: "G2TechSoft",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=c3171b6133a2f8d8&bb=HtY44tjKAMlRZeFarjJnviF3MJ3Gm33G415elftDaKKfQ8g3Nk44qJ5uHaIO3WxY70jqF1to0vFyAc5u8PmTIti0TvCmjjqKq6hToqGHm79ogThRvaRFfIXO3zli-foY&xkcb=SoDd67M3kYpaPMgfTT0JbzkdCdPP&fccid=de01dc8ebc8367c8&vjs=3",
    source: "indeed",
  },
  {
    title: "Full Stack Developer",
    company: "Trymywebsites",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=f64aed8ce91a223c&bb=HtY44tjKAMlRZeFarjJnvi6NjvDXDZ7AX6XRStmCHB6V-LuQJeoSyuNPNztphmH3iTKk9xko7fFYNrJm5ZOd4rjcK4EM63ykouf6YtdnE1s8L_I2sR0VwojG_UUY0Ej5&xkcb=SoDn67M3kYpaPMgfTT0PbzkdCdPP&fccid=928ca289a1be22d1&cmp=Trymywebsites&ti=Full+Stack+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Senior React JS Developer",
    company: "Sumanas Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=5947ce2f54f92823&bb=HtY44tjKAMlRZeFarjJnvv_i8nlsl3I4XD5HcJWhDfoILFUalWPN-b76uHFOUO5xLniEHFvCI5ipUQ0YIndPWDe6XuEhrLjzQFYxfiAUiv0L3xVhZNqYte_I3U50j21-&xkcb=SoBT67M3kYpaPMgfTT0ObzkdCdPP&fccid=77c57e2a11faa4fb&vjs=3",
    source: "indeed",
  },
  {
    title: "React Native Developer",
    company: "Widelast Technology",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=4573ace945f7325a&bb=HtY44tjKAMlRZeFarjJnvpHtxRZpBA5rHt9eY1Y68xLgVAUJPa8Pm3aBjN5GkNgXVniZbp8VDO1oswNqQ06WYc9Qe0Zs0E3j72vN2Q3lCiXUeCJVq-8_8tH_yVsyjc8S&xkcb=SoDO67M3kYpaPMgfTT0NbzkdCdPP&fccid=bb4aacee582af482&vjs=3",
    source: "indeed",
  },
  {
    title: "Full Stack Developer",
    company: "MAARRS",
    location: "Saravanampatti, Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=16d1069470f5ae7d&bb=HtY44tjKAMlRZeFarjJnvioG-Cz1aCqi4hfeevg83BzwL8XG8enBotAKI-_-GW6okiGR0XlFHia3ymTHtMUvR8qiTEJbQYUV27jznRxIaIE5rrR_jntlt9zsR8ixtiyi&xkcb=SoB667M3kYpaPMgfTT0MbzkdCdPP&fccid=cca0927cdd7ec604&cmp=Maarrs&ti=Full+Stack+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Python Developer",
    company: "OneData Software Solutions",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=4c37d59a4c68b454&bb=HtY44tjKAMlRZeFarjJnvi99OltG1cV7uCmrBjX1kNeeYs1eJjaLyWT-ImNCveDSclMWi04z9xzAnoAIPRjzV6UCrKBKOGZn8dqYcMg3OjkpCYAlihc5csKPPpD2g24O&xkcb=SoCT67M3kYpaPMgfTT0DbzkdCdPP&fccid=3e979433fa3524d2&vjs=3",
    source: "indeed",
  },
  {
    title: "SUMMER INTERNSHIP PROGRAM ON MERN STACK 2026",
    company: "LIVE STREAM TECHNOLOGIES",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=fa54ab7ad2245431&bb=HtY44tjKAMlRZeFarjJnvuw45D7blvfTD61twZE7maEC0W3xKnVjaBy-LmgiY2QN7v9mVX9ugl6Q6Xls4jvxVtxV2E8Pmv5eydcVU2AGfS-AFegeD5pIiKGD2xogmXKC&xkcb=SoAn67M3kYpaPMgfTT0CbzkdCdPP&fccid=965f97d589742b0c&cmp=LIVE-STREAM-TECHNOLOGIES&ti=Summer+Intern&vjs=3",
    source: "indeed",
  },
  {
    title: "SUMMER INTERNSHIP PROGRAM ON MERN STACK 2026",
    company: "LIVE STREAM TECHNOLOGIES",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/viewjob?jk=fedcba9876543210",
    source: "indeed",
  },
  {
    title: "AI Developer",
    company: "Nelgates Technologies Private Ltd",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=c83cc79b46b06d71&bb=HtY44tjKAMlRZeFarjJnvm9YzW7cIHEea75b8-AcungVTXbqMBk0ycFrwYzlKldJnLxkO0Florzm9ptpc7xm_5Vl9Tdr33-h2A69VNu6CwrLVRDYREMpKkOshLZwuobp&xkcb=SoC667M3kYpaPMgfTT0BbzkdCdPP&fccid=03f689442825d661&cmp=Nelgates-Technologies-Private-Ltd&ti=Ai+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Mid MERN Developer",
    company: "SolutionChamps Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=893dbfc4c8cf4c6a&bb=HtY44tjKAMlRZeFarjJnvjXIstG2aIo9qPgF6o3TKVinJB_wyU8PoIq04lh8J-a21I-ttIzJfpm1n8XYWXwY3CmlhoOJ76-lBb6ULr_OGBZp8TIvQ4HIbm9XrV3bGsfU&xkcb=SoAO67M3kYpaPMgfTT0AbzkdCdPP&fccid=bcbb311672dfff82&vjs=3",
    source: "indeed",
  },
  {
    title: "Junior Programmer",
    company: "eNova Software and Hardware Solutions Private...",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=f37322f481055cc8&bb=HtY44tjKAMlRZeFarjJnvhvZZqMv_FcEfJnwxR44BpOvt25p8qWzTSsi7omt-yy87hYid8l6afTFrQ4eK8QXesZfPdlgGh89Bbx0OZPSF1HU0gBu4RjI9xcVJCgIt_M3&xkcb=SoCA67M3kYpaPMgfTT0HbzkdCdPP&fccid=6607f4efc5f46f57&cmp=eNova-Software-and-Hardware-Solutions-Private-Limited&ti=Junior+Programmer+Analyst&vjs=3",
    source: "indeed",
  },
  {
    title: "Web Designers / Web Developers / Logo Designers",
    company: "Sudarshan Software Exports",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=1548acb4cef20d79&bb=HtY44tjKAMlRZeFarjJnvjDZ9HudBimFIkCiGINBC1Af21T9V5SDc8DYWvMsxXY0hY8bp6whB0U9GxjXSFT1RWmdhPkdmjN4gVGhEB7fiK1SzZzKe9qjhZewH8CmFPsy&xkcb=SoA067M3kYpaPMgfTT0GbzkdCdPP&fccid=b3479ade96404fe3&vjs=3",
    source: "indeed",
  },
  {
    title: "Tech Lead",
    company: "Userflow",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=767af43c815be160&bb=HtY44tjKAMlRZeFarjJnvpHtxRZpBA5rNfLpZ5Q99MsxKScNx12vYEcscJLMKgnbI5HZ1VjRq-3FyqylCuq66fKGfMqt_rRIoEqhzURB9_b-uhWuE0ULHM6R6_YTi0Jw&xkcb=SoCp67M3kYpaPMgfTT0FbzkdCdPP&fccid=dd616958bd9ddc12&vjs=3",
    source: "indeed",
  },
  {
    title: "UI Designer",
    company: "Invicious Metacorp Private Limited",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=b42d4056f19d565b&bb=PVaoas0xD_CSCMbV3yE4uX_g1Iahgiv6lf38uUyco-oO3B6qpzcW4UVCFQRw_5jt49dGo91bO-pOdt2vrqWK0rU0R_oIeMR5zCNvh35Na6mdNVu7HC1mU7kJLyVwbbJ_&xkcb=SoC_67M3kYpTMFzNzJ0LbzkdCdPP&fccid=4e9776af8774e13a&cmp=Invicious-Metacorp-Private-Limited&ti=User+Interface+Designer&vjs=3",
    source: "indeed",
  },
  {
    title: "Senior Frontend Software Engineer",
    company: "G2TechSoft",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=ae2d35814d23d478&bb=PVaoas0xD_CSCMbV3yE4ufTtWyHuLClFzMPMzjreLIfOxDcpJgvoVnNxrle8n314gTnYt6TcAHmYENUVjobE-Q2e809Ot2vtwH9EBD4482YxCzkazFetLk6KvCe1aDQu&xkcb=SoAL67M3kYpTMFzNzJ0KbzkdCdPP&fccid=de01dc8ebc8367c8&vjs=3",
    source: "indeed",
  },
  {
    title: "Web Developer",
    company: "Mindnotix",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=7b298bdfde58e186&bb=PVaoas0xD_CSCMbV3yE4ua9PraBJHl_cuMnf1gPFB59mVWs_jBNApsxcwN1z024rKdqjxaA0yVm0iKj2kCRVx3anWVHuhTz7ToUsT2gKZJ2a5p9sEWz4xoX3ZjEHq8-I&xkcb=SoCW67M3kYpTMFzNzJ0JbzkdCdPP&fccid=975338f7238270b2&vjs=3",
    source: "indeed",
  },
  {
    title: "Web Developer",
    company: "Bubblz Entertainment",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=8ba5e484b60d9eb3&bb=PVaoas0xD_CSCMbV3yE4uVmgfMQFk66pMBQcB-s1fQPp6zLeDKaUhum2Y15IWIL0gEO8G9btbUlTVNLWkN0RcI2Knd0937BvZNYUv-5Kn64kwxa4IYQ5FEbsjTcZaHuK&xkcb=SoAi67M3kYpTMFzNzJ0IbzkdCdPP&fccid=0e9c3396a2dc97cc&vjs=3",
    source: "indeed",
  },
  {
    title: "Web development track",
    company: "Cloudseed Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=92726267437543dc&bb=PVaoas0xD_CSCMbV3yE4uQV2foMNl24tVNh9_1BTuE2beVQnkyV62aoepKjALaQBQS2IAZdeVkuT60_F4EwQNQZMmTVoeCEV551Ngq1XjCxuyqARJp5RCZvC9iUy2HkW&xkcb=SoCs67M3kYpTMFzNzJ0PbzkdCdPP&fccid=59c6c50a3c40c265&vjs=3",
    source: "indeed",
  },
  {
    title: "Full Stack Intern",
    company: "Bluekode solutions",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=5aef73702798b8d9&bb=PVaoas0xD_CSCMbV3yE4uaqDqoBlYJPRDNIBUX5qxFETfYfmTNODDNwSXs4itwpysMGhDr_u3Ewy6Pr2BPrazQwPbrIayjEDXWQUqWOHaFgn73pDyMbCkfMCl5VLb6VT&xkcb=SoAY67M3kYpTMFzNzJ0ObzkdCdPP&fccid=8a2fff7a1cf1b6e5&cmp=Bluekode-solutions&ti=Full+Stack+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Full Stack Developer",
    company: "Dataspire",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=a90ac5a0c11ccdfe&bb=PVaoas0xD_CSCMbV3yE4uQV2foMNl24t2MVjFddv22sW3pldEvkGG2yWxCkhwjuv1oKDB7DvqpUcVXbxQBupuFkuQy4IosjL397ZPl7kOuEbieDa1I30f10uvYFlMOPa&xkcb=SoCF67M3kYpTMFzNzJ0NbzkdCdPP&fccid=e1ac067dc2ee1de5&vjs=3",
    source: "indeed",
  },
  {
    title: "Senior UI Developer - Figma & React Exp Must - Coimbatore",
    company: "Forar Tech India Private Limited",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=146f17f71db3715d&bb=PVaoas0xD_CSCMbV3yE4uVFbXKGzog0EsY5viGUXuojhwR__Ly48HBGk09zmvldvH25CaC25Tr-qOReaJKdCGAsEDhWXbY-mB0j8f55pcrskjumCi4mutuHvfJdFmNWO&xkcb=SoAx67M3kYpTMFzNzJ0MbzkdCdPP&fccid=bb9ab752c3326441&cmp=Forar-Tech-India-Private-Limited&ti=Front+End+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Senior Frontend Developer",
    company: "Sumanas Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=4e3170d62e261762&bb=PVaoas0xD_CSCMbV3yE4uRzkYqKPENsUdgi08qu0xKuRTtHU_UPbCh9FNDsU6s_8BQjEES0CwSuOEjb-MCKqvJnDTSvqBc6l7OjiQ0jYzSJ-u7UgBuyKtQz9qPSdqIOs&xkcb=SoDY67M3kYpTMFzNzJ0DbzkdCdPP&fccid=77c57e2a11faa4fb&vjs=3",
    source: "indeed",
  },
  {
    title: "Full Stack Developer",
    company: "Infygain Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=7aebdd079e178abf&bb=PVaoas0xD_CSCMbV3yE4ubhitq9e4mVWMMcMWqljgqXDFQOIV9JCYauQgAZI8UoU0oswPaCwCP4824uDwABlvEluNImXYZ8DK1n20b9RmVEiOaY_b-C3ttvg6NR1JiSS&xkcb=SoBs67M3kYpTMFzNzJ0CbzkdCdPP&fccid=289f22a070395509&cmp=Infygain-Technologies&ti=Full+Stack+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "UI/UX Design",
    company: "nurtur.group",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=9256dc16e15741fa&bb=PVaoas0xD_CSCMbV3yE4uedR2GSnQgA-xaqA_HeX45w25o6Y4J3R8iIP_BFUSe7bL0LZoYzVJ7c3DLuagP1GRizDyQFy-nAjK_Sc5XiuyWyIcR88AXZAjY1nOCOjFAev&xkcb=SoDx67M3kYpTMFzNzJ0BbzkdCdPP&fccid=c02ab9cdf15da7de&vjs=3",
    source: "indeed",
  },
  {
    title: "UI/UX Design",
    company: "nurtur.group",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/viewjob?jk=789abcdef0123456",
    source: "indeed",
  },
  {
    title: "Web Developer Intern",
    company: "Eminent Technology",
    location: "Ganapathi, Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=39366f353945e35d&bb=PVaoas0xD_CSCMbV3yE4uQV2foMNl24teYlJ2iOXLEI_4m9be24AJFv0-O5YERmSuh_-Hbhvmp5K-Bu8T0Mh7Xg2A1cshAsvtW4FcSg9NvM95fuNvZ7Wo2oPVpHJewFN&xkcb=SoBF67M3kYpTMFzNzJ0AbzkdCdPP&fccid=f94d90274fb41ddd&cmp=Eminent-Technology&ti=Web+Developer&vjs=3",
    source: "indeed",
  },
  {
    title: "Web Developer",
    company: "PSG Institute of Technology and Applied Research",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=b0036e5a2adef994&bb=PVaoas0xD_CSCMbV3yE4uS3mLWq8pawE33kYu703ouGiouazMN9eV6hmMVZec_XR6NbnSHrcO31Leynd5orJnwbQb8fU82GhimzMn5HoGlqQXdxhqffTvM-CyNP-62kf&xkcb=SoDL67M3kYpTMFzNzJ0HbzkdCdPP&fccid=a38d04f6973ce339&vjs=3",
    source: "indeed",
  },
  {
    title: "MERN Stack / Full Stack Developer",
    company: "ColorWhistle",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=b3652bbf1dada2c2&bb=PVaoas0xD_CSCMbV3yE4uWrRM-48G_ZT1GusFsbR3W0sQDE6_iR1Ws-QpGTCWNeal24FFjJsmuT5F1EDV2mfYQM8KD7zL1D7o3UH5GZw5jG-7MHaZ6GR_0224hK5uzU1&xkcb=SoB_67M3kYpTMFzNzJ0GbzkdCdPP&fccid=a7cd2c103b5c097f&vjs=3",
    source: "indeed",
  },
  {
    title: "Web Developer",
    company: "NGFO Technologies",
    location: "Coimbatore, Tamil Nadu",
    postedHoursAgo: 999,
    link: "https://in.indeed.com/rc/clk?jk=018f3deb483cf523&bb=PVaoas0xD_CSCMbV3yE4uRc_QBYIlynWMsBGKiY03v86d98oUysnuoI8UczXaSxZP5iQYv8qachfUKAv9UDv0gvSICFL3tWLMPF44Bh_oF8pI6sKnoYAI6dyQ7eq_gAo&xkcb=SoDi67M3kYpTMFzNzJ0FbzkdCdPP&fccid=f796ce7d9c981f5d&vjs=3",
    source: "indeed",
  },
];

export const JSEARCH_MOCK_RESULTS = [
  {
    job_id: "dhNzVxdC3SoaE5TYAAAAAA==",
    job_title: "Senior Frontend Developer (React.js / Next.js)",
    employer_name: "RSN GINFO Solutions",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfueliWsAledP7kB3OnTw3QhC7_7_xgjEWvA7E&s=0",
    employer_website: null,
    job_publisher: "Glassdoor",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.glassdoor.co.in/job-listing/senior-frontend-developer-react-js-next-js-rsn-ginfo-solutions-JV_IC2836047_KO0,42_KE43,62.htm?jl=1010115976425",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link:
          "https://www.glassdoor.co.in/job-listing/senior-frontend-developer-react-js-next-js-rsn-ginfo-solutions-JV_IC2836047_KO0,42_KE43,62.htm?jl=1010115976425",
        is_direct: false,
        publisher: "Glassdoor",
      },
    ],
    job_description:
      "coimbatore\n\nfull-time\n\nsenior\n\nJob Description\n\nWe are looking for a highly skilled Senior Frontend Developer with strong expertise in React.js and Next.js to build scalable, high-performance web applications. The ideal candidate should have deep knowledge of modern JavaScript (ES6+), TypeScript, and frontend architectures, along with a strong focus on performance, accessibility , and SEO best practices.\n\nKey Responsibilities\n\nDesign and develop responsive, scalable, and high-performance web applications using React.js and Next.js Build reusable components and frontend libraries for future use Translate UI/UX designs into clean, efficient, and maintainable code Optimize applications for maximum speed, performance, and SEO Implement server-side rendering (SSR), static site generation (SSG), and API integrations in Next.js Collaborate with backend developers, designers, and product teams Ensure cross-browser compatibility and mobile responsiveness Write clean, scalable code using TypeScript and modern JavaScript (ES6+) Conduct code reviews and mentor junior developers Maintain code quality through best practices, linting, and testing Integrate third-party APIs and services Handle state management using tools like Redux, Zustand, or Context API.\n\nRequirements\n\n5–8+ years of experience in frontend development Strong expertise in: React.js Next.js JavaScript (ES6+) TypeScript HTML5 & CSS3 Experience with SSR, SSG, and performance optimization Strong understanding of RESTful APIs and asynchronous programming Familiarity with modern frontend tools and workflows (Webpack, Vite, Babel) Experience with version control systems (Git) Knowledge of responsive design and cross-browser compatibility Understanding of SEO principles in frontend development Experience with CSS frameworks like Tailwind CSS or Bootstrap\n\nQualifications\n\nBachelor’s degree in Computer Science, Engineering, or related field (or equivalent experience)\n\nJob Overview\n\nNumber of Positions\n\n1\n\nSalary Range\n\n11 - 12 INR\n\nPosted Date\n\n4/28/2026\n\nAbout RSNG Info Solutions\n\nFounded\n\n2019\n\nCompany Size\n\n51-200 employees\n\nIndustry\n\ntechnology\n\nWebsite\n\nrsnginfo.com/\n\nContact Information\n\ninfo@rsnginfo.com\n\nAbout\n\nAt RSNGINFO, we prioritize customer needs and dedicate ourselves to quality creations that aim to meet every aspect of our client’s requirements. We collaborate and contribute our expertise to adapt the best ways to improve our product services that are accessible, light, and easy to implement.\n\nSkills\n\nPrimary Skills\n\nreact.jsNext.js",
    job_is_remote: false,
    job_posted_at: "25 days ago",
    job_posted_at_timestamp: 1777334400,
    job_posted_at_datetime_utc: "2026-04-28T00:00:00.000Z",
    job_location: "Coimbatore, Tamil Nadu",
    job_city: "Coimbatore",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 10.9973691,
    job_longitude: 76.9588876,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3DdhNzVxdC3SoaE5TYAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "HO8xl54AW62lGUaQAAAAAA==",
    job_title:
      "Full stack Developer (React.js, Next.js, Node.js, MongoDB) (Coimbatore)",
    employer_name: "BETTER LIVES :)",
    employer_logo: null,
    employer_website: null,
    job_publisher: "Jobrapido.com",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link: "https://in.jobrapido.com/jobpreview/7779675497495003136",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link: "https://in.jobrapido.com/jobpreview/7779675497495003136",
        is_direct: false,
        publisher: "Jobrapido.com",
      },
    ],
    job_description:
      "As an agile Full Stack Developer, you will be doing the system study, analyzing the requirements, building up the logic and writing codes; developing DB structures, and binding them to the I/O layers with APIs; conduct testing with your codes and take it to final deployment. You will be required to document the developments and maintain the source codes in the GIT branches.\n\nExperience 2 - 4+ years\n\nResponsibilities:\n\n⦁ Develop and maintain web applications using various technologies such as PHP, Flutter, Next.js, Node.js, Angular, HTML, CSS, jQuery, Python.\n\n⦁ Collaborate with cross-functional teams including product management, UX designers, and QA to deliver high-quality web applications.\n\n⦁ Participate in the Agile development process including Sprint planning, retrospectives, and daily standups.\n\n⦁ Experience in Azure Devops.\n\n⦁ Develop and maintain RESTful Web Services using JSON and other formats.\n\n⦁ Develop and maintain Full stack code using React.js (Next.js), Node.js, Python, PHP, Angular, HTML, CSS, jQuery.\n\n⦁ Work with database schema and queries using NOSQL and RDBMS (MongoDB, MYSQL, PostgreSQL, etc).\n\n⦁ Execute manual and automated test scripts over the required test cases to ensure high quality and error-free code.\n\n⦁ Implement the required code quality and security checks using various tools to maintain the code in Grade-A condition.\n\n⦁ Push the App, Troubleshoot and debug issues in production and non-production environments.\n\n⦁ Continuously improve the development process by implementing best practices, tools, and techniques.\n\nRequired Skills:\n\n⦁ Bachelor's degree in computer science or related field.\n\n⦁ 2+ years of experience in full-stack App development.\n\n⦁ Strong development skills in Flutter, Next.js Node.js, PHP, and Python.\n\n⦁ Proficiency in App development using HTML, CSS, jQuery, Angular, Dart and Flutter\n\n⦁ Experience with Front end frameworks like Vue.js,React.js,tailwind css,etc are an added advantage.\n\n⦁ Experience with MYSQL, PostgreSQL, or Mongo DB.\n\n⦁ Experience with RESTful Web Services using JSON.\n\n⦁ Familiarity with WebSocket, Gulp, Grunt, npm.\n\n⦁ Experience with Devops and CI/CD pipelines.\n\n⦁ Familiarity with version control systems such as Git/SVN.\n\n⦁ Strong analytical and problem-solving skills.\n\n⦁ Good communication and interpersonal skills.\n\n⦁ Ability to work collaboratively with cross-functional teams in an Agile workplace.",
    job_is_remote: false,
    job_posted_at: "2 days ago",
    job_posted_at_timestamp: 1779321600,
    job_posted_at_datetime_utc: "2026-05-21T00:00:00.000Z",
    job_location: "Coimbatore, Tamil Nadu",
    job_city: "Coimbatore",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 10.9973691,
    job_longitude: 76.9588876,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3DHO8xl54AW62lGUaQAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "a5A_tbE7vLuP2llUAAAAAA==",
    job_title: "Contract Nextjs Developer in Coimbatore",
    employer_name: "Cosmoquick",
    employer_logo:
      "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://cosmoquick.com&size=128",
    employer_website: "https://cosmoquick.com",
    job_publisher: "Cosmoquick",
    job_employment_type: "Contractor",
    job_employment_types: ["CONTRACTOR"],
    job_apply_link:
      "https://cosmoquick.com/hire-contract-in/coimbatore/hire-contract-nextjs-developer",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link:
          "https://cosmoquick.com/hire-contract-in/coimbatore/hire-contract-nextjs-developer",
        is_direct: false,
        publisher: "Cosmoquick",
      },
    ],
    job_description:
      "Hire contract Nextjs Developer candidates in Coimbatore. Project-based engagements.",
    job_is_remote: false,
    job_posted_at: "5 days ago",
    job_posted_at_timestamp: 1779062400,
    job_posted_at_datetime_utc: "2026-05-18T00:00:00.000Z",
    job_location: "Coimbatore, Tamil Nadu",
    job_city: "Coimbatore",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 10.9973691,
    job_longitude: 76.9588876,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3Da5A_tbE7vLuP2llUAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "0YCEmQO_Bu3jDVqAAAAAAA==",
    job_title: "Frontend React.js Developer – Module Lead (Coimbatore)",
    employer_name: "Adhanam Infotech Private",
    employer_logo: null,
    employer_website: null,
    job_publisher: "Jobrapido.com",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link: "https://in.jobrapido.com/jobpreview/9131229550095630336",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link: "https://in.jobrapido.com/jobpreview/9131229550095630336",
        is_direct: false,
        publisher: "Jobrapido.com",
      },
    ],
    job_description:
      "Frontend React.js Developer – Module Lead\n\nExperience: 5+ Years\n\nLocation: Chennai (On-site Only)\n\nWe are seeking a skilled and proactive Frontend Developer – Module Lead to spearhead the development of high-quality, scalable web applications using React.js. This role involves both hands-on coding and mentoring responsibilities within a fast-paced, collaborative setting.\n\nKey Responsibilities:\n\n- Lead the design and development of complex frontend modules using React.js.\n- Translate UI/UX designs into responsive, pixel-perfect interfaces.\n- Mentor junior team members and enforce clean, maintainable code practices.\n- Collaborate with cross-functional teams to ensure seamless integration and delivery.\n\nRequired Skills:\n\n- Strong expertise in React.js, Redux/Context API, and React Hooks.\n- Proficient in Java Script (ES6+), HTML5, CSS3, and RESTful API integration.\n- Version control using Git, and hands-on experience with Jest or React Testing Library.\n- Exposure to Next.js and/or Type Script is a strong advantage.\n\nApply Now\n\nIf you're ready to lead impactful backend development in a fast-moving environment, we’d love to hear from you.\n\nSend your resume to:\n\nSubject Line: Application – Frontend React.js Developer Module Lead – [Your Name]\n\nLearn more about .",
    job_is_remote: false,
    job_posted_at: "2 days ago",
    job_posted_at_timestamp: 1779321600,
    job_posted_at_datetime_utc: "2026-05-21T00:00:00.000Z",
    job_location: "Coimbatore, Tamil Nadu",
    job_city: "Coimbatore",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 10.9973691,
    job_longitude: 76.9588876,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3D0YCEmQO_Bu3jDVqAAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "y9S2o74dSREVnhVMAAAAAA==",
    job_title: "Platform Development Lead - Python/Next.js",
    employer_name: "ATOM Systems Pvt Ltd",
    employer_logo: null,
    employer_website: null,
    job_publisher: "Jooble",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link: "https://in.jooble.org/jdp/-4526381311976839995",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link: "https://in.jooble.org/jdp/-4526381311976839995",
        is_direct: false,
        publisher: "Jooble",
      },
    ],
    job_description:
      "Description :Overview :This role will lead the transition from a working prototype to a scalable, multi-user platform, enabling client development teams to safely build and extend reporting agents through controlled APIs and reusable components.You will be the first engineering lead oEshore, responsible for hands-on development, platform design, and establishing engineering standards.Key Responsibilities :Platform Build & Architecture :- Refactor an existing Python-based prototype into a modular, production-grade platform- Define clear service boundaries (API layer, orchestration, agent runtime, data access)- Build reusable components that allow extension without exposing core engine logicAgent Framework & Orchestration :- Design and implement frameworks for AI agents and reporting workflows- Build orchestration for multi-step execution (deterministic + AI-driven)- Ensure outputs are traceable, auditable, and suitable for financial reportingDeveloper Enablement :Enable internal/client developers to :- build and deploy reporting agents- Reuse approved components- Access platform capabilities via APIs (without direct code access)- Implement access controls and abstraction layersFull Stack Development :- Lead development across :- Backend : Python, FastAPI- Frontend : Next.js- Real-time : WebSocketsCode Governance & DevOps :- Own development workflows in Azure DevOps- Branching strategy, PRs, code reviews, merges- Set up CI/CD pipelines, environments (dev/test/prod), and release processes- Ensure code quality, testing, and maintainability standardsTeam Leadership (Near-term) :- Act as the technical anchor oEshore- Mentor and guide future hires as the team scales- Establish best practices across code, documentation, and deliveryRequired Skills :- Strong experience in Python backend development (FastAPI or similar)- Experience with React / Next.js- Familiarity with WebSockets or real-time systems- Experience building APIs and scalable backend systems- Hands-on experience with Azure DevOps (repos, pipelines, PR workflows)- Understanding of modular architecture, access control, and system design- Ability to operate in an early-stage, fast-evolving environmentPreferred/Nice to Have :- Experience with AI/LLM-based systems or agent workflows- Exposure to financial services / insurance / reporting systems- Experience with Databricks or similar data platforms- Familiarity with workflow orchestration or event-driven systemsMode : Contract to HireShift : UK shift (ref:hirist.tech)",
    job_is_remote: false,
    job_posted_at: "27 days ago",
    job_posted_at_timestamp: 1777161600,
    job_posted_at_datetime_utc: "2026-04-26T00:00:00.000Z",
    job_location: "Coimbatore, Tamil Nadu",
    job_city: "Coimbatore",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 10.9973691,
    job_longitude: 76.9588876,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3Dy9S2o74dSREVnhVMAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "je6Bu-j_VeT6gSv3AAAAAA==",
    job_title: "Software Developer (.NET, React, Node.js)",
    employer_name: "Linkedin",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxyTZu4zcn-0WWOR_fIwe9mqDyPnG-5MuNhcOf&s=0",
    employer_website: "https://about.linkedin.com",
    job_publisher: "Jooble",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link: "https://in.jooble.org/jdp/3612141280614880838",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link: "https://in.jooble.org/jdp/3612141280614880838",
        is_direct: false,
        publisher: "Jooble",
      },
    ],
    job_description:
      "Apply Now! E-mail at View email address on easyhiring.pro | (WA) on View phone number on easyhiring.pro\n\n﻿Job Title: Software Developer / Sr. Software Developer (.NET, React, Node.js)\n\nExperience: Minimum 3 - 8 years of professional software development experience\n\nJob Summary: We are looking for a highly skilled Software Developer to design, develop, and maintain scalable web applications using .NET, React, and Node.js. The ideal candidate is a hands-on engineer who enjoys solving complex problems, mentoring junior developers, and collaborating across teams to deliver high-quality software solutions.\n\nKey Responsibilities:\n• Design, develop, and maintain full-stack web applications using .NET (C#), React, and Node.js\n• Build and consume RESTful APIs and backend services\n• Develop responsive, reusable, and performant UI components using React\n• Write clean, maintainable, and well-documented code following best practices\n• Optimize application performance, scalability, and security\n• Collaborate with product managers, designers, and other engineers to deliver features end-to-end\n• Participate in code reviews and provide technical guidance to junior developers\n• Troubleshoot, debug, and resolve production issues\n• Contribute to architecture decisions and technical roadmap planning\n\nRequired Skills & Qualifications:\n• 5+ years of hands-on experience in software development\n• Strong experience with .NET / C# (ASP.NET Core, Web APIs)\n• Solid proficiency in React.js (hooks, state management, component architecture)\n• Experience with Node.js and backend development\n• Strong understanding of JavaScript/TypeScript, HTML5, and CSS3\n• Experience working with SQL and/or NoSQL databases\n• Familiarity with RESTful services, authentication, and authorization\n• Experience with Git and modern CI/CD pipelines\n• Strong problem-solving and debugging skills\n• Excellent communication and collaboration abilities\n\nPreferred / Nice-to-Have Skills:\n• Experience with cloud platforms (Azure, AWS, or GCP)\n• Knowledge of microservices architecture\n• Experience with Docker and containerization\n• Familiarity with unit testing and automated testing frameworks\n• Experience working in Agile/Scrum environments\n\nEducation: Bachelor’s degree in Computer Science, Engineering, or a related field (or equivalent practical experience)\n\nApply Now! E-mail at View email address on easyhiring.pro | (WA) on View phone number on easyhiring.pro.",
    job_is_remote: false,
    job_posted_at: "7 days ago",
    job_posted_at_timestamp: 1778889600,
    job_posted_at_datetime_utc: "2026-05-16T00:00:00.000Z",
    job_location: "Coimbatore, Tamil Nadu",
    job_city: "Coimbatore",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 10.9973691,
    job_longitude: 76.9588876,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3Dje6Bu-j_VeT6gSv3AAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "EJSnzrjIgdtHYwWiAAAAAA==",
    job_title: "Lead React Developer",
    employer_name: "Geekx",
    employer_logo:
      "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://getmereferred.com&size=128",
    employer_website: null,
    job_publisher: "Getmereferred.com",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://getmereferred.com/job-listing/lead-react-developer-geekx-coimbatore-5-to-10-years-experience-f269849c-6a88-4fa6-ae7f-8af0a8fa18ee",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link:
          "https://getmereferred.com/job-listing/lead-react-developer-geekx-coimbatore-5-to-10-years-experience-f269849c-6a88-4fa6-ae7f-8af0a8fa18ee",
        is_direct: false,
        publisher: "Getmereferred.com",
      },
    ],
    job_description:
      "Job SummaryWe are looking for a Senior React Developer with strong hands-on experience in building scalable, high-performance web applications. The ideal candidate should have deep expertise in React.js and modern frontend ecosystems, along with practical experience leveraging AI-powered tools and integrations to enhance user experience, productivity, and application intelligence. Key ResponsibilitiesDesign, develop, and maintain complex, scalable frontend applications using React.js. Architect reusable components, hooks, and design systems following best practices. Collaborate closely with product managers, designers, backend engineers, and AI teams . Integrate AI-powered features such as chat interfaces, recommendations, summarization, or automation into web applications. Work with AI tools and APIs (e.g., OpenAI, LangChain-based services, vector search UIs) for frontend consumption. Optimize applications for performance, accessibility, responsiveness, and SEO . Lead frontend technical decisions, code reviews, and mentor junior developers. Ensure clean, maintainable, and testable code using modern testing frameworks. Stay up to date with emerging frontend trends, React ecosystem updates, and AI-driven UI innovations. Required Skills & Qualifications5+ years of strong hands-on experience in React.js and JavaScript (ES6+) . Expertise in HTML5, CSS3, Tailwind / Material UI / Ant Design , and responsive design. Strong experience with state management (Redux, Zustand, React Query, Context API). Hands-on experience with REST APIs and GraphQL . Practical exposure to AI tools and integrations (e.g., AI chatbots, copilots, AI-assisted workflows). Experience consuming LLM-based APIs and handling streaming responses in UI. Strong understanding of frontend architecture, performance optimization, and security best practices . Familiarity with Git, CI/CD pipelines, and agile development processes . Good to HaveExperience with Next.js , SSR, and server components. Exposure to TypeScript in large-scale applications. Knowledge of prompt-driven UI patterns and AI UX design. Experience with data visualization libraries (Recharts, D3, Chart.js). Familiarity with cloud platforms (AWS, GCP, Azure). Prior experience working on AI-driven products or SaaS platforms .",
    job_is_remote: false,
    job_posted_at: null,
    job_posted_at_timestamp: null,
    job_posted_at_datetime_utc: null,
    job_location: "Coimbatore, Tamil Nadu",
    job_city: "Coimbatore",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 10.9973691,
    job_longitude: 76.9588876,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3DEJSnzrjIgdtHYwWiAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "Ija2Z37E0kYAjnhnAAAAAA==",
    job_title: "Sumanas Technologies - Senior Frontend Developer - React.js",
    employer_name: "Sumanas Technologies Private Limited",
    employer_logo:
      "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://hirist.tech&size=128",
    employer_website: null,
    job_publisher: "Hirist",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.hirist.tech/j/sumanas-technologies-senior-frontend-developer-reactjs-1616301",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link:
          "https://www.hirist.tech/j/sumanas-technologies-senior-frontend-developer-reactjs-1616301",
        is_direct: false,
        publisher: "Hirist",
      },
    ],
    job_description:
      "Position : Senior Frontend Developer\n\nExperience : 4 - 10 years\n\nLocation : Madurai/Coimbatore\n\nEmployment Type : Full-time\n\nAbout the Role :\n\nWe are looking for a skilled Senior Frontend Developer with strong expertise in React.js to join our dynamic team. The ideal candidate will have hands-on experience in building scalable, high-performing web applications with a focus on clean code, testing, and responsive design.\n\nKey Responsibilities :\n\n- Develop and maintain high-quality, scalable frontend applications using React.js and Next.js.\n\n- Implement state management using Redux and Redux Toolkit (RTK).\n\n- Write and maintain unit and end-to-end tests using frameworks like Jest, Cypress, or Mocha.\n\n- Work with Material-UI (MUI) and reusable component libraries to deliver consistent UI.\n\n- Optimize performance and ensure cross-browser compatibility.\n\n- Collaborate with backend developers to integrate with RESTful APIs and WebSockets.\n\n- Utilize advanced JavaScript concepts (Web Workers, Promise Pool, IndexedDB, Canvas, etc.) for performance optimization.\n\n- Participate in Agile ceremonies, ensuring timely delivery of high-quality features.\n\n- (Optional) Contribute to backend integration with PHP and Laravel (Blade templating) when required.\n\nRequired Skills :\n\n- Excellent verbal and written communication skills.\n\n- 4+ years of proven experience in frontend development with React.js.\n\n- Proficiency in testing frameworks (Jest, Cypress, Mocha, etc.).\n\n- Strong expertise in Redux & Redux Toolkit (RTK).\n\n- Knowledge of Material-UI (MUI) or similar component libraries.\n\n- Advanced understanding of JavaScript concepts (Web Workers, IndexedDB, Promises, Canvas, etc.).\n\n- Solid understanding of RESTful APIs and WebSockets.\n\n- Basic knowledge of PHP & Laravel (preferred but not mandatory).\n\nPreferred Skills :\n\n- Experience in responsive design and cross-browser compatibility.\n\n- Familiarity with Git/version control systems.\n\n- Knowledge of Agile methodologies.",
    job_is_remote: false,
    job_posted_at: null,
    job_posted_at_timestamp: null,
    job_posted_at_datetime_utc: null,
    job_location: "India   (+3 others)",
    job_city: null,
    job_state: null,
    job_country: null,
    job_latitude: null,
    job_longitude: null,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3DIja2Z37E0kYAjnhnAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "MASFoHzy53suXKTkAAAAAA==",
    job_title: "Trika Technologies - UI Technical Lead - React.js/Next.js",
    employer_name: "TRIKA TECHNOLOGIES PRIVATE LIMITED",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ02wBhkMhyf2zKNy9FPY7k-0lSzd9oZbwoaWqr&s=0",
    employer_website: null,
    job_publisher: "Jooble",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link: "https://in.jooble.org/jdp/6879012708920189964",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link: "https://in.jooble.org/jdp/6879012708920189964",
        is_direct: false,
        publisher: "Jooble",
      },
    ],
    job_description:
      "Description :- Own and define frontend architecture using React.js / Next.js across client projects- Lead end-to-end UI delivery ensuring quality, scalability, and timelines- Act as the primary frontend SPOC for clients, handling requirements, solutioning, and escalations- Write hands-on code for complex, high-impact UI modules- Drive performance optimization (Core Web Vitals, SSR/SSG, code splitting, lazy loading)- Establish and enforce coding standards, best practices, and design systems- Lead and mentor a team of UI developers, including code reviews and skill development- Collaborate with backend, UX, QA, and DevOps teams for seamless delivery- Ensure high code quality, testing practices, and maintainability across projects- Manage multiple projects and stakeholders, ensuring smooth execution and client satisfactionWHAT WE NEED IN YOU :- Strong foundation in JavaScript (ES6+), HTML5, and CSS3, with a clear understanding of core concepts and browser fundamentals- Proven hands-on experience in React.js, including Hooks, component lifecycle, state management, and performance tuning- Practical experience with Next.js, covering SSR, SSG, routing, and middleware for building scalable and SEO-optimized applications- Ability to design and implement scalable, maintainable frontend architectures for complex applications- Strong experience in component-driven development, including building and managing reusable design systems- Proficiency in state management solutions such as Redux, Zustand, or Context API, with a clear understanding of when to use each- Hands-on experience with Code splitting, lazy loading, Rendering optimization and Core Web Vitals improvement- Strong experience integrating REST APIs / GraphQL- Should be actively coding, not just managing and also strong in code reviews, mentoring, and technical guidance.- Able to handle complex UI problems and critical modules independently and ability to manage multiple projects and priorities- Experience working directly with clients/stakeholders during discussions, demos and escalations.- Ability to translate business requirements into technical solutions- Experience working in Agile/Scrum environmentsGood to Have (Adds Strong Advantage) :- Exposure to Node.js / Express.js- Experience with TypeScript- Familiarity with cloud platforms (AWS / Vercel)- Knowledge of e-commerce or high-traffic applicationsQUALIFICATION :- Graduate - BE / Btech or equivalent.- 7 to 10 years of experience- Self motivated and quick learner with excellent problem solving skills.- A good team player with nice communication skills.- Energy and real passion to work in a startup environment. Visit our website - (ref:hirist.tech)",
    job_is_remote: false,
    job_posted_at: null,
    job_posted_at_timestamp: null,
    job_posted_at_datetime_utc: null,
    job_location: "Coimbatore, Tamil Nadu",
    job_city: "Coimbatore",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 10.9973691,
    job_longitude: 76.9588876,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3DMASFoHzy53suXKTkAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
  {
    job_id: "QPihrP_6lovD57eNAAAAAA==",
    job_title: "Web Developer — PHP/MySQL + Python/Next.js",
    employer_name: "Kustom Pro",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjGnZgA_O2Cn24gZdAv05-JUtdkylfi0ZeJMW4&s=0",
    employer_website: null,
    job_publisher: "Glassdoor",
    job_employment_type: "Full–time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.glassdoor.co.in/job-listing/web-developer-php-mysql-python-next-js-kustom-pro-JV_IC2836484_KO0,38_KE39,49.htm?jl=1010121706944",
    job_apply_is_direct: false,
    apply_options: [
      {
        apply_link:
          "https://www.glassdoor.co.in/job-listing/web-developer-php-mysql-python-next-js-kustom-pro-JV_IC2836484_KO0,38_KE39,49.htm?jl=1010121706944",
        is_direct: false,
        publisher: "Glassdoor",
      },
    ],
    job_description:
      "We are looking for a Web Developer with 2–5 years of experience and strong PHP/MySQL skills to maintain our existing website and support a new platform being built with Python FastAPI, Next.js, TypeScript, and Supabase.\n\nYou do not need to know every technology listed. Strong fundamentals, clean code, problem-solving ability, and willingness to learn are most important. Candidate must be located in Tirupur.\n\nResponsibilities\n• Maintain and improve PHP/MySQL web applications\n• Support backend development in Python FastAPI\n• Help build frontend features in Next.js and TypeScript\n• Work with MySQL and PostgreSQL/Supabase databases\n• Write clean, secure, and well-organised code\n• Optimise database queries and application performance\n• Support third-party API integrations such as Stripe, Resend, Twilio, Claude, and n8n\n• Contribute to shared UI components using Tailwind CSS and Radix UI, with training provided\n• Follow team standards for schema migrations, with training provided on Alembic\n• Troubleshoot and fix bugs across existing and new systems\n\nRequired Skills\n• 2–5 years of hands-on web development experience\n• Strong PHP and MySQL experience\n• Good knowledge of HTML, CSS, JavaScript, and REST APIs\n• Basic understanding of relational databases\n• Familiarity with Git\n• Ability to write clear, maintainable code\n• Strong problem-solving skills\n• Willingness to learn Python FastAPI, Next.js, TypeScript, and Supabase\n• Clear written and spoken English\n• Must be based in or able to work on-site in Tirupur\n\nBonus Skills\n• Python, FastAPI, React, Next.js, or TypeScript\n• PostgreSQL or Supabase\n• Alembic or other database migration tools\n• Tailwind CSS or Radix UI\n• Stripe, Twilio, Resend, n8n, or webhook integrations\n• AI/LLM API integrations such as Claude or OpenAI\n\nApplication restricted only to candidated located in Tirupur.\n\nJob Types: Permanent, Full-time\n\nPay: ₹25,000.00 - ₹30,000.00 per month\n\nExperience:\n• Web Developer: 2 years (Required)\n\nLocation:\n• Tiruppur, Tamil Nadu (Required)\n\nWork Location: In person",
    job_is_remote: false,
    job_posted_at: "21 days ago",
    job_posted_at_timestamp: 1777680000,
    job_posted_at_datetime_utc: "2026-05-02T00:00:00.000Z",
    job_location: "Tiruppur, Tamil Nadu",
    job_city: "Tiruppur",
    job_state: "Tamil Nadu",
    job_country: "IN",
    job_latitude: 11.1085242,
    job_longitude: 77.3410656,
    job_benefits: null,
    job_benefits_strings: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=in&hl=en&udm=8#vhid=vt%3D20/docid%3DQPihrP_6lovD57eNAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_salary_string: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {},
    job_onet_soc: null,
    job_onet_job_zone: null,
    employer_reviews: null,
  },
];

export const SEARCH_API_HR_RESULTS_MOCK = [
  {
    position: 1,
    title: "Contact Us",
    link: "https://allcaretherapies.com/en-us/about/contact",
    source: "All Care Therapies",
    domain: "allcaretherapies.com",
    displayed_link: "https://allcaretherapies.com › en-us › about › contact",
    snippet:
      "Contact All Care Therapies by phone, email, or online form. Reach our patient intake, provider relations, careers, and corporate teams.",
    snippet_highlighted_words: ["All Care Therapies", "careers"],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAkFBMVEVHcEz1+/z////////7/f41mLj////////////////////////////J09vQ6/T////xmjlHoL7xlzAWPlv6+/oZQV4GNVTk8PU+nLv2v4mVydsAKUzT4Ob97Nn+9uxts8zi5unypE/74cT4zKK8xs5ZqsX62Lfzr2pQaX+83OeOnqw4WXF9j54xU2yotL9rgpSNJ2z2AAAAHHRSTlMAnQ4Itf7ZTAEqc+7N0dH////////////////+0DH/CgAAAXVJREFUKJF1k+m6giAQhslUQisUEFTUzLTNlvu/uzNgkWebHz7A6zcbA0LWVmhJIj+M49CPyBK2c/OwT5352JszsqDfbEE+DK/pD1vjdzgcvs+67r0KsQm8QsTp6v2+cVoCaOV94hWMFZ+4Hkix2x4TMOeYQtilq6E5sSRhhXAVLRFxf3Z7ELJ97Q4Iitz6wIzb5OgOIuS8isJCdnDQR67G5gU/QUMU/w3NJ0axUkL8ditEq2IUlsFQXpR4lWkTEu3jedfXEPmXIA+AK2ieqfNU0/aaaSl176NIBWma5vmuEqYWdhD9Wcos47KKEFFDnho8VNAidmr6u0GZHFsC7SuNNE2DnapZUlejzDjnmb5C+xCurBJoKbpa3LRlnPfQeLiylzRNFaWVBZzLq7kyuOztbtIGF0ofk1CeN2QaBbzdBZNfKp46M5meN/g9n3hb5kEOKQlxllxqedvg+WheysHCUfPx1s9H0w61AoOEqrb9MdT/PIcvRX8uvHsKag0AAAAASUVORK5CYII=",
  },
  {
    position: 2,
    title: "Careers",
    link: "https://allcaretherapies.com/en-us/careers",
    source: "All Care Therapies",
    domain: "allcaretherapies.com",
    displayed_link: "https://allcaretherapies.com › en-us › careers",
    snippet:
      "Your Career, Your Way. Join 400+ licensed therapists nationwide. Speech and occupational therapy roles available in all 50 states via telehealth.",
    snippet_highlighted_words: ["therapy", "all"],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAkFBMVEVHcEz1+/z////////7/f41mLj////////////////////////////J09vQ6/T////xmjlHoL7xlzAWPlv6+/oZQV4GNVTk8PU+nLv2v4mVydsAKUzT4Ob97Nn+9uxts8zi5unypE/74cT4zKK8xs5ZqsX62Lfzr2pQaX+83OeOnqw4WXF9j54xU2yotL9rgpSNJ2z2AAAAHHRSTlMAnQ4Itf7ZTAEqc+7N0dH////////////////+0DH/CgAAAXVJREFUKJF1k+m6giAQhslUQisUEFTUzLTNlvu/uzNgkWebHz7A6zcbA0LWVmhJIj+M49CPyBK2c/OwT5352JszsqDfbEE+DK/pD1vjdzgcvs+67r0KsQm8QsTp6v2+cVoCaOV94hWMFZ+4Hkix2x4TMOeYQtilq6E5sSRhhXAVLRFxf3Z7ELJ97Q4Iitz6wIzb5OgOIuS8isJCdnDQR67G5gU/QUMU/w3NJ0axUkL8ditEq2IUlsFQXpR4lWkTEu3jedfXEPmXIA+AK2ieqfNU0/aaaSl176NIBWma5vmuEqYWdhD9Wcos47KKEFFDnho8VNAidmr6u0GZHFsC7SuNNE2DnapZUlejzDjnmb5C+xCurBJoKbpa3LRlnPfQeLiylzRNFaWVBZzLq7kyuOztbtIGF0ofk1CeN2QaBbzdBZNfKp46M5meN/g9n3hb5kEOKQlxllxqedvg+WheysHCUfPx1s9H0w61AoOEqrb9MdT/PIcvRX8uvHsKag0AAAAASUVORK5CYII=",
  },
  {
    position: 3,
    title: "Leadership",
    link: "https://allcaretherapies.com/about/leadership",
    source: "All Care Therapies",
    domain: "allcaretherapies.com",
    displayed_link: "https://allcaretherapies.com › about › leadership",
    snippet:
      "Donna Panero. Head of VP. Donna has over 15 years of HR leadership in telehealth and healthcare sectors, serving as Head of...",
    snippet_highlighted_words: ["HR"],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAkFBMVEVHcEz1+/z////////7/f41mLj////////////////////////////J09vQ6/T////xmjlHoL7xlzAWPlv6+/oZQV4GNVTk8PU+nLv2v4mVydsAKUzT4Ob97Nn+9uxts8zi5unypE/74cT4zKK8xs5ZqsX62Lfzr2pQaX+83OeOnqw4WXF9j54xU2yotL9rgpSNJ2z2AAAAHHRSTlMAnQ4Itf7ZTAEqc+7N0dH////////////////+0DH/CgAAAXVJREFUKJF1k+m6giAQhslUQisUEFTUzLTNlvu/uzNgkWebHz7A6zcbA0LWVmhJIj+M49CPyBK2c/OwT5352JszsqDfbEE+DK/pD1vjdzgcvs+67r0KsQm8QsTp6v2+cVoCaOV94hWMFZ+4Hkix2x4TMOeYQtilq6E5sSRhhXAVLRFxf3Z7ELJ97Q4Iitz6wIzb5OgOIuS8isJCdnDQR67G5gU/QUMU/w3NJ0axUkL8ditEq2IUlsFQXpR4lWkTEu3jedfXEPmXIA+AK2ieqfNU0/aaaSl176NIBWma5vmuEqYWdhD9Wcos47KKEFFDnho8VNAidmr6u0GZHFsC7SuNNE2DnapZUlejzDjnmb5C+xCurBJoKbpa3LRlnPfQeLiylzRNFaWVBZzLq7kyuOztbtIGF0ofk1CeN2QaBbzdBZNfKp46M5meN/g9n3hb5kEOKQlxllxqedvg+WheysHCUfPx1s9H0w61AoOEqrb9MdT/PIcvRX8uvHsKag0AAAAASUVORK5CYII=",
  },
  {
    position: 4,
    title: "Talk to a Recruiter | All Care Therapies Careers",
    link: "https://allcaretherapies.com/careers/connect",
    source: "All Care Therapies",
    domain: "allcaretherapies.com",
    displayed_link: "https://allcaretherapies.com › careers › connect",
    snippet:
      "Fill out the form and a recruiter will follow up within 1-2 business days. You can also email us at hr.recruiting@allcaretherapies.com. Do not fill. Name *.",
    snippet_highlighted_words: ["hr.recruiting@allcaretherapies.com"],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAkFBMVEVHcEz1+/z////////7/f41mLj////////////////////////////J09vQ6/T////xmjlHoL7xlzAWPlv6+/oZQV4GNVTk8PU+nLv2v4mVydsAKUzT4Ob97Nn+9uxts8zi5unypE/74cT4zKK8xs5ZqsX62Lfzr2pQaX+83OeOnqw4WXF9j54xU2yotL9rgpSNJ2z2AAAAHHRSTlMAnQ4Itf7ZTAEqc+7N0dH////////////////+0DH/CgAAAXVJREFUKJF1k+m6giAQhslUQisUEFTUzLTNlvu/uzNgkWebHz7A6zcbA0LWVmhJIj+M49CPyBK2c/OwT5352JszsqDfbEE+DK/pD1vjdzgcvs+67r0KsQm8QsTp6v2+cVoCaOV94hWMFZ+4Hkix2x4TMOeYQtilq6E5sSRhhXAVLRFxf3Z7ELJ97Q4Iitz6wIzb5OgOIuS8isJCdnDQR67G5gU/QUMU/w3NJ0axUkL8ditEq2IUlsFQXpR4lWkTEu3jedfXEPmXIA+AK2ieqfNU0/aaaSl176NIBWma5vmuEqYWdhD9Wcos47KKEFFDnho8VNAidmr6u0GZHFsC7SuNNE2DnapZUlejzDjnmb5C+xCurBJoKbpa3LRlnPfQeLiylzRNFaWVBZzLq7kyuOztbtIGF0ofk1CeN2QaBbzdBZNfKp46M5meN/g9n3hb5kEOKQlxllxqedvg+WheysHCUfPx1s9H0w61AoOEqrb9MdT/PIcvRX8uvHsKag0AAAAASUVORK5CYII=",
  },
  {
    position: 5,
    title: "Working at All Care Therapies",
    link: "https://www.glassdoor.com/Overview/Working-at-All-Care-Therapies-EI_IE4894828.11,29.htm",
    source: "Glassdoor",
    domain: "www.glassdoor.com",
    displayed_link: "https://www.glassdoor.com › Overview › Working-at-A...",
    snippet:
      "See what employees say it's like to work at All Care Therapies. Salaries, reviews, and more - all posted by employees working at All Care Therapies.",
    snippet_highlighted_words: ["All Care Therapies", "All Care Therapies"],
    rich_snippet: {
      detected_extensions: {
        rating: 4.1,
        reviews: 31,
      },
      extensions: ["4.1", "(31)"],
    },
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAYFBMVEX////8/v33/PrU7+XE6Nrh9O3x+vfs+PN+zq4lrXkvsoBqx6O+59Z2y6kOpmwAoWMTq3OJ07ZKuo0AomTM7OC45NK14tFcwZqn3smc2sIbrXYqsX2v4c06tYZUv5U/tohXSID7AAAApElEQVR4Ac3SRQKDQBAAway7Dq7/f2XcPafQRwpYXS0ghF4bJpTxVy6k0sbiF+h8CDE9V2xl9iHSVzMiOYDE10+KstpWMlZWZe1Dza+QO7VLN41WysMd1mGXb9vtfOARAeCA8CuGcMRddxPqus5vsek7pbrO8JulDFU7bpFVw64C3a4dDypE+3zbWjcCTOwpig4C6BI9x17Nkrza7pIy/Pl6/LsNfZYMoaxng94AAAAASUVORK5CYII=",
  },
  {
    position: 6,
    title: "All Care Therapies",
    link: "https://www.linkedin.com/company/allcaretherapies",
    source: "LinkedIn · All Care Therapies",
    domain: "www.linkedin.com",
    displayed_link: "3.5K+ followers",
    snippet:
      "All Care Therapies provides speech, occupational, and physical therapy—virtually and in person. With clinics in California, Texas, and Nevada, we support ...",
    snippet_highlighted_words: [
      "All Care Therapies provides speech, occupational, and physical therapy",
    ],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAm0lEQVR4AWP4//8/RRhMyLfs3sNQvOk/KRikB24ATNB2yhEQJtoQuAEwzVAAYtPVAMJe4Cjf8l+0bsd/RkIGQAGc/ej9t/+TDt/7/+vPXzD/6Yfv/+2nHSXWAAT49P33/z9//4HZl559JM2Aqm3XwXyXGcfA/H///pFmgFj9DjCfp3IrTIgkA5ADbbAbQA6mKDPp9x7YBTOAIgwAVba5DGceMlQAAAAASUVORK5CYII=",
  },
  {
    position: 7,
    title: "All Care Therapies careers in Los Angeles, CA",
    link: "https://www.indeed.com/cmp/All-Care-Therapies/locations/CA/Los%20Angeles",
    source: "Indeed",
    domain: "www.indeed.com",
    displayed_link: "https://www.indeed.com › ... › All Care Therapies",
    snippet:
      "Learn about working at All Care Therapies in Los Angeles, CA. See jobs, salaries, employee reviews and more for Los Angeles, CA location.",
    snippet_highlighted_words: ["All Care Therapies"],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAflBMVEUAAAD///////////////////////////////////////////////+/zuZvkMZQd7pAa7Sgtdnv8/gAOptgg8AgUqcgU6evweCAnc0QRqF/nc3v8vhwkMcwXq3f5vLP2uz////f5/JfhMB/nM0wX66AnM1PeLqPqdOftdrv8/mN6/jEAAAAIXRSTlMAEGCfz+//XyCQj98w/////////////////////////6AQ1BAWAAABD0lEQVR4AYWThRZCIQxAR+11h939/z+oHECHGNd4sbvR8IJxIRWikiJiEBInCl+IGHxYim+kfnqGARkpkj/jRVnVVdMaIw/yi7qr+7IaxolXg7n4dDZfGHEojGFG4/q3XK3RsSE9jV3+SqevC6ToRrbmdjc84m3ddeOOCAkAQ8Oo6++7BzURFANuB3DQ/8dOgwTuWjjpAnjW8YEKAqS5KU0dLVyoIEGZYdnOr8veH4YCN+5vWGGBVtxc68IXFFLqrus8QYH8LUjY/hYE8N9CBEz9FBhA8ksQZLmpQJeblAiFxNtyoZCxYNMvu252CzY+2fa3fVU84/nfg0NgyXs8YeATb0lUJTGEML61x5+T7DuGyRy8BcS3+wAAAABJRU5ErkJggg==",
  },
  {
    position: 8,
    title: "Careers at All Care Therapies",
    link: "https://careers.smartrecruiters.com/AllCareTherapies",
    source: "SmartRecruiters",
    domain: "careers.smartrecruiters.com",
    displayed_link: "https://careers.smartrecruiters.com › AllCareTherapies",
    snippet:
      "We have plenty of treatment options for children and adults of all ages. Work from anywhere in the world. We offer flexible schedules with evening and weekend ...",
    snippet_highlighted_words: ["all"],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAyVBMVEX////2/fj6/vuz68Jv3I4002c302lh2oSs6bw+1G1H1XJL1nVA1G7n6uuD4Jw402rByMsADCeXo6hF1XF835dkeYAAM0LA78yL4qPu+vGg57PO/9hGXWvV2tsaRFCuuLuMlZp8hozK8dRM2XY9rGkAM0js7u8AOUcAIzXa3d8AKjsAGC2W5Ks7pWgYOk+jr7Jwg4p3qJBUZG0cN0VCvG4JL0kaP1Avgl81SlYAKDkkX1YAAiMnalkAHzlAU17b8OIKK0nY9+Bfl36hAR48AAABH0lEQVR4AcXRVYKDMBQF0FtBH50q7tTd3bv/RQ2p238PzhNIgt9LJPBdMpXmeJ4TxC8JKV6SKSYrnIhYJoO7vyzdZdNALl94xCQiKvJF4hUiUkpQtRyudJ4VGCaQsNgtZzuaC8D1fIBikohMEPqIeCpXqp5WQ6zeqEVZIjmNZr7VaofoFMvdnqeB6WuDISuMMGqNx+N8zcyWJz3Pw1m9Pu2WKWuCxcYNHxLR1KvjrF+fzc/BBQsuWbDM2l5os1WZtQ0a43Fr3TSzVN5sfVwM6r0yyQKgLnZhE50iEb/Hlb88TOJSC8yxIxHLvPNPcTIpQilNnMRuuQhPZJli7MxIBp6ZSpHusiW8SqT5a5gt2Ydjic9msxxZJr7aH/cJ/NY/zWsc5SGFEeIAAAAASUVORK5CYII=",
  },
  {
    position: 9,
    title: "Employee Notices",
    link: "https://allcaretherapies.com/en-us/employee-notices",
    source: "All Care Therapies",
    domain: "allcaretherapies.com",
    displayed_link: "https://allcaretherapies.com › en-us › employee-notices",
    snippet:
      "Required employee notices and labor law postings for All Care Therapies employees in California and Texas.",
    snippet_highlighted_words: ["All Care Therapies"],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAkFBMVEVHcEz1+/z////////7/f41mLj////////////////////////////J09vQ6/T////xmjlHoL7xlzAWPlv6+/oZQV4GNVTk8PU+nLv2v4mVydsAKUzT4Ob97Nn+9uxts8zi5unypE/74cT4zKK8xs5ZqsX62Lfzr2pQaX+83OeOnqw4WXF9j54xU2yotL9rgpSNJ2z2AAAAHHRSTlMAnQ4Itf7ZTAEqc+7N0dH////////////////+0DH/CgAAAXVJREFUKJF1k+m6giAQhslUQisUEFTUzLTNlvu/uzNgkWebHz7A6zcbA0LWVmhJIj+M49CPyBK2c/OwT5352JszsqDfbEE+DK/pD1vjdzgcvs+67r0KsQm8QsTp6v2+cVoCaOV94hWMFZ+4Hkix2x4TMOeYQtilq6E5sSRhhXAVLRFxf3Z7ELJ97Q4Iitz6wIzb5OgOIuS8isJCdnDQR67G5gU/QUMU/w3NJ0axUkL8ditEq2IUlsFQXpR4lWkTEu3jedfXEPmXIA+AK2ieqfNU0/aaaSl176NIBWma5vmuEqYWdhD9Wcos47KKEFFDnho8VNAidmr6u0GZHFsC7SuNNE2DnapZUlejzDjnmb5C+xCurBJoKbpa3LRlnPfQeLiylzRNFaWVBZzLq7kyuOztbtIGF0ofk1CeN2QaBbzdBZNfKp46M5meN/g9n3hb5kEOKQlxllxqedvg+WheysHCUfPx1s9H0w61AoOEqrb9MdT/PIcvRX8uvHsKag0AAAAASUVORK5CYII=",
  },
  {
    position: 10,
    title: "All Care Therapies - Overview, News & Similar companies",
    link: "https://www.zoominfo.com/c/all-care-therapies/355557160",
    source: "ZoomInfo",
    domain: "www.zoominfo.com",
    displayed_link: "https://www.zoominfo.com › all-care-therapies",
    snippet:
      "All Care Therapies contact info: Phone number: (818) 894-2273 Website: www.allcaretherapies.com What does All Care Therapies do? All Care ...",
    snippet_highlighted_words: ["All Care Therapies contact info"],
    favicon:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA90lEQVR4AWMAgfcKEgqvpEX3v5YRfQ+k/9Mav5QSWw+yE245zGI64/dgR7yWEVkPF6Q/3s+AKkD/UBhoB/wf/A4YdQARAJ/a4eMAooLzrYXx/z+PH9HbAZiW/338kF4OwLT895VLQL4RBQ7AxCRZ/lpTmX7Z8J2bE9zyn8eOwiyntQMQlv/9+BFs+feVyyksByi3nH4O+FSYC09g32bPoFdRjGn5l94u+tYFn+trSLGcutnwa28XuuU0dABhy+nrAByAkPxQcsBoi2jUAcBu2UCHwP6BsvyFlNgGhucSEgoDEQqgDjHIbgYQADFAnVR6WQz08H6Y5QAohh4QgciXDwAAAABJRU5ErkJggg==",
  },
];
